### ISSUE TITLE
Cannot Run on Android WebView

### ISSUE THREAD

**Issue by tomeroto** [holtwick/briefing#135]
Hi friends, 

I want to embed briefing to android webview, but its only show blank page. 

How to fix it? 

thabk you.

**Comment by holtwick** [comment]
Consider the iframe integration, see bullet No. 2 here https://github.com/holtwick/briefing#use-in-your-own-projects

**Comment by holtwick** [comment]
Or see here how to https://github.com/holtwick/briefing/tree/legacy/android

**Comment by tomeroto** [comment]
I was try, but error has come:

```
[vite] connecting... -- From line 205 of http://28.28.28.21:8080/@vite/client
[vite] connected. -- From line 285 of http://28.28.28.21:8080/@vite/client
Uncaught TypeError: Cannot read properties of null (reading 'zeed') -- From line 103 of http://28.28.28.21:8080/node_modules/.vite/deps/chunk-OPWQOTBS.js?v=fde0cec8
```

please help.

**Comment by holtwick** [comment]
So you are self-hosting? What is your setup? Docker? Did you try other browsers than Android Webview?

**Comment by tomeroto** [comment]
Yes I used it to self hosting, and I setup via git clone and NPM install.

**Comment by holtwick** [comment]
Well then please look into the Android code at https://github.com/holtwick/briefing/tree/legacy/android It might have a solution for you. Please note, `https` is a requirement in order to get video and audio working. Although the error message seems to point to a missing dependency. But since you already did `npm install` I have no further idea how to fix it. Sorry.
