### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by gfyre** [holtwick/briefing#46]
It would be really cool to see a chat feature in this platform.

The way to do it whilst maintaining anonymity is by allowing a user to set a nickname thereby allowing everyone to know who texted what.

**Comment by holtwick** [comment]
`messages` is a global hub for messages. `.emit` sends them and `.on` listens to them. This is unrelated to Socket or WebRTC communication.

**Comment by holtwick** [comment]
Correct, this is only for UI communication. I guess you are looking for something like this for peer2peer communication: https://github.com/holtwick/briefing/blob/master/app/src/logic/webrtc.js#L201

**Comment by YashGovekar** [comment]
> Correct, this is only for UI communication. I guess you are looking for something like this for peer2peer communication: https://github.com/holtwick/briefing/blob/master/app/src/logic/webrtc.js#L201

Great thanks! Really appreciate your help.
I will make a PR if successful 😀

**Comment by holtwick** [comment]
Thanks @YashGovekar Your PR is awesome and almost ready to be merged  🎉

Just FYI: I am currently also working on a chat implementation at https://viidoo.chat It will not be possible to migrate this back to Briefing due to technical implementation details.

**Comment by holtwick** [comment]
I reviewed your code. It is super close to being merged. If you could address the following small issues, it would be perfect. Thanks.

- [ ] The input field scrolls with the messages (see screenshot); it would be great if it would stick to the bottom

Nice to have:

- [ ] It would be nice, if the chat icon could stay highlighted while it is open, like "Settings" and "Share" icons do
- [ ] The time and name in each message might also fit into one line and have the same font size to save some space?
- [ ] On new messages it would be nice if they scroll into the view automatically
- [ ] If the chat is opened it would be great if the main input field is already focussed; (not sure if this is a good idea on mobile too, probably you can reuse this? https://github.com/holtwick/briefing/blob/master/app/src/components/app-welcome.vue#L436

Otherwise, awesome work! Thanks a lot!

![CleanShot 2021-05-03 at 11 19 01@2x](https://user-images.githubusercontent.com/49557/116860281-9d5d1500-ac01-11eb-8817-c58f6f9f24f3.png)

**Comment by holtwick** [comment]
Fixed by the PR of @YashGovekar Thanks a lot!

**Comment by YashGovekar** [comment]
> Fixed by the PR of @YashGovekar Thanks a lot!

You're welcome :)
