### ISSUE TITLE
Exception: DOMException: Could not start video source

### ISSUE THREAD

**Issue by UnnikrishnanBhargavakurup** [holtwick/briefing#69]
When I try to access the application in two browsers in the same computer I'm getting the following error, is this an expected behavior?

```
index.js:52 Exception: DOMException: Could not start video source
d @ index.196eee2a.js?__WB_REVISION__=42c4cc5bfe7384689a3f:1
state.js:210 Media error Could not start video source
```

How we can fix this?

**Comment by holtwick** [comment]
See https://www.twilio.com/docs/video/build-js-video-application-recommendations-and-best-practices#media-errors


NotReadableError | 1. Failed starting capture of a audio track2. Failed starting capture of a video track3. Could not start audio source4. Could not start video source5. The I/O read operation failed | The browser could not start media capture with the input device even  after the user gave permission, probably because another app or tab has  reserved the input device | User should close all other apps and tabs that have reserved the  input device and reload your app, or worst case, restart the browser
-- | -- | -- | --

**Comment by holtwick** [comment]
Closing. Recommended user action "User should close all other apps and tabs that have reserved the input device and reload your app, or worst case, restart the browser"
